### ISSUE TITLE
Chapter_8 reenactment_pix2pix reenactment_train_pix2pix.ipynb have no dataset

### ISSUE THREAD

**Issue by zm274310577** [PacktPublishing/Hands-On-Generative-AI-with-Python-and-TensorFlow-2#1]
Chapter_8/reenactment_pix2pix/reenactment_train_pix2pix.ipynb have no dataset data.zip

**Comment by raghavbali** [comment]
@zm274310577 Kindly read through the instructions, the data generation script is based on code snippets discussed in the **Facial landmarks** section
